<?php

namespace SD\CoreBundle\Repository;

/**
 * BookingLabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingLabelRepository extends \Doctrine\ORM\EntityRepository
{
}
