<?php

namespace SD\CoreBundle\Repository;

/**
 * BookingLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingLineRepository extends \Doctrine\ORM\EntityRepository
{
}
