<?php

namespace SD\CoreBundle\Repository;

/**
 * BookingLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingLineRepository extends \Doctrine\ORM\EntityRepository
{
	public function getBookingLines($booking)
	{
	$qb = $this->createQueryBuilder('bl');
	$qb->select('bl.date date');
	$qb->addSelect('p.id planificationID');
	$qb->addSelect('pp.id planificationPeriodID');
	$qb->addSelect('pl.id planificationLineID');
	$qb->addSelect('t.id timetableID');
	$qb->addSelect('tl.id timetableLineID');
	$qb->where('bl.booking = :booking')->setParameter('booking', $booking);
	$qb->innerJoin('bl.planification', 'p');
	$qb->innerJoin('bl.planificationPeriod', 'pp');
	$qb->innerJoin('bl.planificationLine', 'pl');
	$qb->innerJoin('bl.timetable', 't');
	$qb->innerJoin('bl.timetableLine', 'tl');
	$qb->orderBy('bl.date', 'ASC');
	$qb->addOrderBy('p.id', 'ASC');
	$qb->addOrderBy('pp.id', 'ASC');
	$qb->addOrderBy('pl.id', 'ASC');
	$qb->addOrderBy('t.id', 'ASC');
	$qb->addOrderBy('tl.id', 'ASC');
	$query = $qb->getQuery();
	$results = $query->getResult();
	return $results;
	}
}
