<?php

namespace SD\CoreBundle\Repository;

/**
 * BookingUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingUserRepository extends \Doctrine\ORM\EntityRepository
{
}
