<?php

namespace SD\CoreBundle\Repository;

/**
 * PlanificationLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificationLineRepository extends \Doctrine\ORM\EntityRepository
{
}
