<?php

namespace SD\CoreBundle\Repository;

/**
 * PlanificationResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificationResourceRepository extends \Doctrine\ORM\EntityRepository
{
}
