<?php

namespace SD\CoreBundle\Repository;

/**
 * PlanificationResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificationResourceRepository extends \Doctrine\ORM\EntityRepository
{
	// Recherche les ressources d'une periode de planification
	public function getResources($planificationPeriod)
    {
    $queryBuilder = $this->createQueryBuilder('pr');
    $queryBuilder->where('pr.planificationPeriod = :planificationPeriod')->setParameter('planificationPeriod', $planificationPeriod);
    $queryBuilder->orderBy('pr.order', 'ASC');
   
    $query = $queryBuilder->getQuery();
    $results = $query->getResult();
    return $results;
    }

	// Compte les periodes de planification d'une ressource
    public function getPlanificationPeriodsCount($resource)
    {
    $queryBuilder = $this->createQueryBuilder('pr');
    $queryBuilder->select($queryBuilder->expr()->count('pr'));
    $queryBuilder->where('pr.resource = :resource')->setParameter('resource', $resource);

    $query = $queryBuilder->getQuery();
    $singleScalar = $query->getSingleScalarResult();
    return $singleScalar;
    }

	// Construit le Query Builder d'une ressource planifiee
	public function getResourcePlanifiedQB()
    {
    $queryBuilder = $this->createQueryBuilder('pr');
    $queryBuilder->where('pr.resource = r.id');
    return $queryBuilder;
    }
}
