<?php

namespace SD\CoreBundle\Repository;

/**
 * PlanificationPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanificationPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
