<?php

namespace SD\CoreBundle\Repository;

/**
 * QueryBookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QueryBookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQueryBookingCount($file)
    {
    $queryBuilder = $this->createQueryBuilder('qb');
    $queryBuilder->select($queryBuilder->expr()->count('qb'));
    $queryBuilder->where('qb.file = :file')->setParameter('file', $file);

    $query = $queryBuilder->getQuery();
    $singleScalar = $query->getSingleScalarResult();
    return $singleScalar;
    }
	
    public function getDisplayedQueryBooking($file, $firstRecordIndex, $maxRecord)
    {
    $queryBuilder = $this->createQueryBuilder('qb');
    $queryBuilder->where('qb.file = :file')->setParameter('file', $file);
    $queryBuilder->orderBy('qb.name', 'ASC');
    $queryBuilder->setFirstResult($firstRecordIndex);
    $queryBuilder->setMaxResults($maxRecord);
   
    $query = $queryBuilder->getQuery();
    $results = $query->getResult();
    return $results;
    }
}
