<?php

namespace SD\CoreBundle\Repository;

/**
 * ResourceClassificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceClassificationRepository extends \Doctrine\ORM\EntityRepository
{
}
