<?php

namespace SD\CoreBundle\Repository;

/**
 * ResourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function getResourcesCount($file)
    {
    $queryBuilder = $this->createQueryBuilder('r');
    $queryBuilder->select($queryBuilder->expr()->count('r'));
    $queryBuilder->where('r.file = :file')->setParameter('file', $file);

    $query = $queryBuilder->getQuery();
    $singleScalar = $query->getSingleScalarResult();
    return $singleScalar;
    }
	
	public function getResources($file)
    {
    $queryBuilder = $this->createQueryBuilder('r');
    $queryBuilder->where('r.file = :file')->setParameter('file', $file);
    $queryBuilder->orderBy('r.type', 'ASC');
    $queryBuilder->addOrderBy('r.internal', 'DESC');
    $queryBuilder->addOrderBy('r.code', 'ASC');
    $queryBuilder->addOrderBy('r.name', 'ASC');
   
    $query = $queryBuilder->getQuery();
    $results = $query->getResult();
    return $results;
    }

	public function getDisplayedResources($file, $firstRecordIndex, $maxRecord)
    {
    $queryBuilder = $this->createQueryBuilder('r');
    $queryBuilder->where('r.file = :file')->setParameter('file', $file);
    $queryBuilder->orderBy('r.type', 'ASC');
    $queryBuilder->addOrderBy('r.internal', 'DESC');
    $queryBuilder->addOrderBy('r.code', 'ASC');
    $queryBuilder->addOrderBy('r.name', 'ASC');
    $queryBuilder->setFirstResult($firstRecordIndex);
    $queryBuilder->setMaxResults($maxRecord);
   
    $query = $queryBuilder->getQuery();
    $results = $query->getResult();
    return $results;
    }

	public function getResourcesToPlanify($file, $type, $resourcePlanifiedQB)
    {
    $qb = $this->createQueryBuilder('r');
    $qb->where('r.file = :file')->setParameter('file', $file);
    $qb->andWhere('r.type = :type')->setParameter('type', $type);
    
	$qb->andWhere($qb->expr()->not($qb->expr()->exists($resourcePlanifiedQB->getDQL())));
     
    $qb->orderBy('r.name', 'ASC');

    $query = $qb->getQuery();
    $results = $query->getResult();
    return $results;
    }

	public function getResourceTypesToPlanify($file, $resourcePlanifiedQB)
    {
    $qb = $this->createQueryBuilder('r');
    $qb->select('r.type');
    $qb->addSelect($qb->expr()->count('r'));
    $qb->where('r.file = :file')->setParameter('file', $file);
    
	$qb->andWhere($qb->expr()->not($qb->expr()->exists($resourcePlanifiedQB->getDQL())));
     
    $qb->groupBy('r.type');
    $qb->orderBy('r.type', 'ASC');

    $query = $qb->getQuery();
    $results = $query->getResult();
    return $results;
    }

    // Retourne le nombre de ressources d'une classification
    public function getResourcesCount_RC($resourceClassification)
    {
    $queryBuilder = $this->createQueryBuilder('r');
    $queryBuilder->select($queryBuilder->expr()->count('r'), count);
    $queryBuilder->where('r.classification = :classification')->setParameter('classification', $resourceClassification);

    $query = $queryBuilder->getQuery();
    $singleScalar = $query->getSingleScalarResult();
    return $singleScalar;
    }

    // Retourne les ressources d'une classification
    public function getResources_RC($resourceClassification)
    {
	$queryBuilder = $this->createQueryBuilder('r');
    $queryBuilder->where('r.classification = :classification')->setParameter('classification', $resourceClassification);
	$queryBuilder->orderBy('r.name', 'ASC');

	$query = $queryBuilder->getQuery();
	$results = $query->getResult();
	return $results;
    }
}
