<?php

namespace SD\CoreBundle\Repository;

/**
 * TimetableRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimetableRepository extends \Doctrine\ORM\EntityRepository
{
    public function getTimetablesCount($file)
    {
    $queryBuilder = $this->createQueryBuilder('t');
    $queryBuilder->select($queryBuilder->expr()->count('t'));
    $queryBuilder->where('t.file = :file')->setParameter('file', $file);

    $query = $queryBuilder->getQuery();
    $singleScalar = $query->getSingleScalarResult();
    return $singleScalar;
    }
	
    public function getDisplayedTimetables($file, $firstRecordIndex, $maxRecord)
    {
    $queryBuilder = $this->createQueryBuilder('t');
    $queryBuilder->where('t.file = :file')->setParameter('file', $file);
    $queryBuilder->orderBy('t.name', 'ASC');
    $queryBuilder->setFirstResult($firstRecordIndex);
    $queryBuilder->setMaxResults($maxRecord);
   
    $query = $queryBuilder->getQuery();
    $results = $query->getResult();
    return $results;
    }
	
    public function getTimetablesQB($file)
    {
    $queryBuilder = $this->createQueryBuilder('t');
	$queryBuilder->where('t.file = :file')->setParameter('file', $file);
    $queryBuilder->orderBy('t.name', 'ASC');
   
    return $queryBuilder;

/*
    $query = $queryBuilder->getQuery();
    $results = $query->getResult();
    return $results;
*/
    }
}
