<?php

namespace SD\CoreBundle\Repository;

/**
 * UserParameterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserParameterRepository extends \Doctrine\ORM\EntityRepository
{
}
