<?php

namespace SD\CoreBundle\Repository;

/**
 * UserFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFileRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserFilesCount($file)
    {
    $queryBuilder = $this->createQueryBuilder('uf');
    $queryBuilder->select($queryBuilder->expr()->count('uf'));
    $queryBuilder->where('uf.file = :file')->setParameter('file', $file);

    $query = $queryBuilder->getQuery();
    $singleScalar = $query->getSingleScalarResult();
    return $singleScalar;
    }

    public function getDisplayedUserFiles($file, $firstRecordIndex, $maxRecord)
    {
    $queryBuilder = $this->createQueryBuilder('uf');
    $queryBuilder->where('uf.file = :file')->setParameter('file', $file);
    $queryBuilder->orderBy('uf.email', 'ASC');
    $queryBuilder->setFirstResult($firstRecordIndex);
    $queryBuilder->setMaxResults($maxRecord);
   
    $query = $queryBuilder->getQuery();
    $results = $query->getResult();
    return $results;
    }
}
