<?php

namespace SD\CoreBundle\Repository;

/**
 * UserFileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFileRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserFilesCount($file)
    {
    $queryBuilder = $this->createQueryBuilder('uf');
    $queryBuilder->select($queryBuilder->expr()->count('uf'));
    $queryBuilder->where('uf.file = :file')->setParameter('file', $file);

    $query = $queryBuilder->getQuery();
    $singleScalar = $query->getSingleScalarResult();
    return $singleScalar;
    }

    public function getDisplayedUserFiles($file, $firstRecordIndex, $maxRecord)
    {
    $queryBuilder = $this->createQueryBuilder('uf');
    $queryBuilder->where('uf.file = :file')->setParameter('file', $file);
    $queryBuilder->orderBy('uf.firstName', 'ASC');
    $queryBuilder->addOrderBy('uf.lastName', 'ASC');
    $queryBuilder->setFirstResult($firstRecordIndex);
    $queryBuilder->setMaxResults($maxRecord);
   
    $query = $queryBuilder->getQuery();
    $results = $query->getResult();
    return $results;
    }

	public function getUserFilesFromInternalResourceClassification($file, $classificationCode)
    {
    $qb = $this->createQueryBuilder('uf');
    $qb->where('uf.file = :file')->setParameter('file', $file);
    $qb->andWhere('uf.resourceUser = :resourceUser')->setParameter('resourceUser', 1);
	$qb->innerJoin('uf.resource', 'r', Expr\Join::WITH, $qb->expr()->andX($qb->expr()->eq('r.internal', '?1'), $qb->expr()->eq('r.code', '?2')));
    $qb->orderBy('uf.firstName', 'ASC');
    $qb->addOrderBy('uf.lastName', 'ASC');
    $qb->setParameter(1, 1); 
    $qb->setParameter(2, $classificationCode); 

    $query = $qb->getQuery();
    $results = $query->getResult();
    return $results;
    }
}
