# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    
    my.subscriber:
        class: SD\CoreBundle\Event\SBEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments: ["@security.token_storage", "@translator"]

    sb_user.user_listener:
        class: SD\UserBundle\Event\UserListener
        arguments: ["security.token_storage", "@doctrine", "@logger"]
        tags:
            - { name: kernel.event_subscriber }

    sd_core.calendar_listener:
        class: SD\CoreBundle\Event\CalendarEventListener
        arguments: ["@router", "@security.token_storage", "@doctrine", "@logger"]
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }

    sd_core.validator.timetableLineBeginningTime:
        class: SD\CoreBundle\Validator\TimetableLineBeginningTimeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: sd_core_timetableLineBeginningTime }

    sd_core.validator.timetableLineEndTime:
        class: SD\CoreBundle\Validator\TimetableLineEndTimeValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: sd_core_timetableLineEndTime }

    sd.twig.sd_extension:
        class: SD\CoreBundle\Twig\SDExtension
        tags:
            - { name: twig.extension }
        arguments: ["@translator"]
