# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    
    my.subscriber:
        class: SD\CoreBundle\Event\SBEventSubscriber
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        arguments:
            - "@security.token_storage"

    sb_user.user_listener:
        class: SD\UserBundle\Event\UserListener
        arguments: ["security.token_storage", "@doctrine", "@logger"]
        tags:
            - { name: kernel.event_subscriber }
