sd_core_homepage:
    path:     /
    defaults: { _controller: SDCoreBundle:Default:index }

sd_core_administration:
    path:     /administration
    defaults: { _controller: SDCoreBundle:Default:administration }


sd_core_file_list:
    path:     /file/list/{pageNumber}
    defaults: { _controller: SDCoreBundle:File:index }

sd_core_file_add:
    path:     /file/add
    defaults: { _controller: SDCoreBundle:File:add }

sd_core_file_edit:
    path:     /file/edit/{fileID}
    defaults: { _controller: SDCoreBundle:File:edit }
    requirements:
        fileID: \d+

sd_core_file_modify:
    path:     /file/modify/{fileID}
    defaults: { _controller: SDCoreBundle:File:modify }
    requirements:
        fileID: \d+

sd_core_file_delete:
    path:     /file/delete/{fileID}
    defaults: { _controller: SDCoreBundle:File:delete }
    requirements:
        fileID: \d+

sd_core_file_foreign:
    path:     /file/foreign/{fileID}
    defaults: { _controller: SDCoreBundle:File:foreign }
    requirements:
        fileID: \d+

sd_core_file_set_current:
    path:     /file/setcurrent/{fileID}
    defaults: { _controller: SDCoreBundle:File:set_current }
    requirements:
        fileID: \d+


sd_core_userFile_list:
    path:     /userfile/list/{pageNumber}
    defaults: { _controller: SDCoreBundle:UserFile:index }

sd_core_userFile_email:
    path:     /userfile/email
    defaults: { _controller: SDCoreBundle:UserFile:email }

sd_core_userFile_add:
    path:     /userfile/add/{email}
    defaults: { _controller: SDCoreBundle:UserFile:add }

sd_core_userFile_edit:
    path:     /userfile/edit/{userFileID}
    defaults: { _controller: SDCoreBundle:UserFile:edit }
    requirements:
        userFileID: \d+

sd_core_userFile_modify:
    path:     /userfile/modify/{userFileID}
    defaults: { _controller: SDCoreBundle:UserFile:modify }
    requirements:
        userFileID: \d+

sd_core_userFile_delete:
    path:     /userfile/delete/{userFileID}
    defaults: { _controller: SDCoreBundle:UserFile:delete }
    requirements:
        userFileID: \d+

sd_core_userFile_resource:
    path:     /userfile/resource/{userFileID}
    defaults: { _controller: SDCoreBundle:UserFile:resource }
    requirements:
        userFileID: \d+


sd_core_label_list:
    path:     /label/list/{pageNumber}
    defaults: { _controller: SDCoreBundle:Label:index }

sd_core_label_add:
    path:     /label/add
    defaults: { _controller: SDCoreBundle:Label:add }

sd_core_label_edit:
    path:     /label/edit/{labelID}
    defaults: { _controller: SDCoreBundle:Label:edit }
    requirements:
        labelID: \d+

sd_core_label_modify:
    path:     /label/modify/{labelID}
    defaults: { _controller: SDCoreBundle:Label:modify }
    requirements:
        labelID: \d+

sd_core_label_delete:
    path:     /label/delete/{labelID}
    defaults: { _controller: SDCoreBundle:Label:delete }
    requirements:
        labelID: \d+

sd_core_activity_list:
    path:     /activity/list/{pageNumber}
    defaults: { _controller: SDCoreBundle:Activity:index }

sd_core_activity_add:
    path:     /activity/add
    defaults: { _controller: SDCoreBundle:Activity:add }

sd_core_activity_edit:
    path:     /activity/edit/{activityID}
    defaults: { _controller: SDCoreBundle:Activity:edit }
    requirements:
        activityID: \d+

sd_core_activity_modify:
    path:     /activity/modify/{activityID}
    defaults: { _controller: SDCoreBundle:Activity:modify }
    requirements:
        activityID: \d+

sd_core_activity_delete:
    path:     /activity/delete/{activityID}
    defaults: { _controller: SDCoreBundle:Activity:delete }
    requirements:
        activityID: \d+


sd_core_timetable_list:
    path:     /timetable/list/{pageNumber}
    defaults: { _controller: SDCoreBundle:Timetable:index }

sd_core_timetable_add:
    path:     /timetable/add
    defaults: { _controller: SDCoreBundle:Timetable:add }

sd_core_timetable_edit:
    path:     /timetable/edit/{timetableID}
    defaults: { _controller: SDCoreBundle:Timetable:edit }
    requirements:
        timetableID: \d+

sd_core_timetable_modify:
    path:     /timetable/modify/{timetableID}
    defaults: { _controller: SDCoreBundle:Timetable:modify }
    requirements:
        timetableID: \d+

sd_core_timetable_delete:
    path:     /timetable/delete/{timetableID}
    defaults: { _controller: SDCoreBundle:Timetable:delete }
    requirements:
        timetableID: \d+

sd_core_timetable_addline:
    path:     /timetable/addline/{timetableID}
    defaults: { _controller: SDCoreBundle:Timetable:add_line }
    requirements:
        timetableID: \d+

sd_core_timetable_modifyline:
    path:     /timetable/modifyline/{timetableID}/{timetableLineID}
    defaults: { _controller: SDCoreBundle:Timetable:modify_line }
    requirements:
        timetableID: \d+
        timetableLineID: \d+

sd_core_timetable_deleteline:
    path:     /timetable/deleteline/{timetableID}/{timetableLineID}
    defaults: { _controller: SDCoreBundle:Timetable:delete_line }
    requirements:
        timetableID: \d+
        timetableLineID: \d+

sd_core_timetable_foreign_delete:
    path:     /timetable/foreigndelete/{timetableID}
    defaults: { _controller: SDCoreBundle:Timetable:foreign_delete }
    requirements:
        timetableID: \d+

sd_core_timetable_foreign_update:
    path:     /timetable/foreignupdate/{timetableID}
    defaults: { _controller: SDCoreBundle:Timetable:foreign_update }
    requirements:
        timetableID: \d+


sd_core_resourceclassification_display:
    path:     /resourceclassification/display/{resourceType}
    defaults: { _controller: SDCoreBundle:ResourceClassification:index }

sd_core_resourceclassification_activateinternal:
    path:     /resourceclassification/activateinternal/{resourceType}/{classificationCode}
    defaults: { _controller: SDCoreBundle:ResourceClassification:activate_internal }

sd_core_resourceclassification_unactivateinternal:
    path:     /resourceclassification/unactivateinternal/{resourceType}/{classificationCode}
    defaults: { _controller: SDCoreBundle:ResourceClassification:unactivate_internal }

sd_core_resourceclassification_activateexternal:
    path:     /resourceclassification/activateexternal/{resourceType}/{resourceClassificationID}
    defaults: { _controller: SDCoreBundle:ResourceClassification:activate_external }

sd_core_resourceclassification_unactivateexternal:
    path:     /resourceclassification/unactivateexternal/{resourceType}/{resourceClassificationID}
    defaults: { _controller: SDCoreBundle:ResourceClassification:unactivate_external }

sd_core_resourceclassification_add:
    path:     /resourceclassification/add/{resourceType}
    defaults: { _controller: SDCoreBundle:ResourceClassification:add }

sd_core_resourceclassification_modify:
    path:     /resourceclassification/modify/{resourceType}/{resourceClassificationID}
    defaults: { _controller: SDCoreBundle:ResourceClassification:modify }
    requirements:
        resourceClassificationID: \d+

sd_core_resourceclassification_delete:
    path:     /resourceclassification/delete/{resourceType}/{resourceClassificationID}
    defaults: { _controller: SDCoreBundle:ResourceClassification:delete }
    requirements:
        resourceClassificationID: \d+

sd_core_resourceclassification_foreign:
    path:     /resourceclassification/foreign/{resourceType}/{resourceClassificationID}
    defaults: { _controller: SDCoreBundle:ResourceClassification:foreign }
    requirements:
        resourceClassificationID: \d+


sd_core_resource_list:
    path:     /resource/list/{pageNumber}
    defaults: { _controller: SDCoreBundle:Resource:index }

sd_core_resource_classification:
    path:     /resource/classification
    defaults: { _controller: SDCoreBundle:Resource:classification }

sd_core_resource_add:
    path:     /resource/add
    defaults: { _controller: SDCoreBundle:Resource:add }

sd_core_resource_addinternal:
    path:     /resource/addinternal/{type}/{code}
    defaults: { _controller: SDCoreBundle:Resource:add_internal }

sd_core_resource_addexternal:
    path:     /resource/addexternal/{type}/{resourceClassificationID}
    defaults: { _controller: SDCoreBundle:Resource:add_external }

sd_core_resource_edit:
    path:     /resource/edit/{resourceID}
    defaults: { _controller: SDCoreBundle:Resource:edit }
    requirements:
        resourceID: \d+

sd_core_resource_modify:
    path:     /resource/modify/{resourceID}
    defaults: { _controller: SDCoreBundle:Resource:modify }
    requirements:
        resourceID: \d+

sd_core_resource_delete:
    path:     /resource/delete/{resourceID}
    defaults: { _controller: SDCoreBundle:Resource:delete }
    requirements:
        resourceID: \d+

sd_core_resource_foreign:
    path:     /resource/foreign/{resourceID}
    defaults: { _controller: SDCoreBundle:Resource:foreign }
    requirements:
        resourceID: \d+


sd_core_planification_list:
    path:     /planification/list/{pageNumber}
    defaults: { _controller: SDCoreBundle:Planification:index }

sd_core_planification_type:
    path:     /planification/type
    defaults: { _controller: SDCoreBundle:Planification:type }

sd_core_planification_init_resource:
    path:     /planification/initresource/{type}/{resourceIDList}
    defaults: { _controller: SDCoreBundle:Planification:init_resource, resourceIDList: null }

sd_core_planification_validate_init_resource:
    path:     /planification/validateinitresource/{type}/{resourceIDList}
    defaults: { _controller: SDCoreBundle:Planification:validate_init_resource }

sd_core_planification_update_resource:
    path:     /planification/updateresource/{planificationID}/{planificationPeriodID}/{resourceIDList}
    defaults: { _controller: SDCoreBundle:Planification:update_resource, resourceIDList: null }
    requirements:
        planificationID: \d+
        planificationPeriodID: \d+

sd_core_planification_validate_update_resource:
    path:     /planification/validateupdateresource/{planificationID}/{planificationPeriodID}/{resourceIDList}
    defaults: { _controller: SDCoreBundle:Planification:validate_update_resource }
    requirements:
        planificationID: \d+
        planificationPeriodID: \d+

sd_core_planification_edit_lp:
    path:     /planification/editlp/{planificationID}
    defaults: { _controller: SDCoreBundle:Planification:editLastPeriod }
    requirements:
        planificationID: \d+

sd_core_planification_edit:
    path:     /planification/edit/{planificationID}/{planificationPeriodID}
    defaults: { _controller: SDCoreBundle:Planification:edit }
    requirements:
        planificationID: \d+
        planificationPeriodID: \d+

sd_core_planification_modify:
    path:     /planification/modify/{planificationID}/{planificationPeriodID}
    defaults: { _controller: SDCoreBundle:Planification:modify }
    requirements:
        planificationID: \d+
        planificationPeriodID: \d+

sd_core_planification_delete:
    path:     /planification/delete/{planificationID}/{planificationPeriodID}
    defaults: { _controller: SDCoreBundle:Planification:delete }
    requirements:
        planificationID: \d+
        planificationPeriodID: \d+

sd_core_planification_line:
    path:     /planification/line/{planificationID}/{planificationPeriodID}
    defaults: { _controller: SDCoreBundle:Planification:line }
    requirements:
        planificationID: \d+
        planificationPeriodID: \d+


sd_core_queryBooking_list:
    path:     /queryBooking/list/{pageNumber}
    defaults: { _controller: SDCoreBundle:QueryBooking:index }

sd_core_queryBooking_add:
    path:     /queryBooking/add
    defaults: { _controller: SDCoreBundle:QueryBooking:add }

sd_core_queryBooking_edit:
    path:     /queryBooking/edit/{queryBookingID}
    defaults: { _controller: SDCoreBundle:QueryBooking:edit }
    requirements:
        queryBookingID: \d+

sd_core_queryBooking_modify:
    path:     /queryBooking/modify/{queryBookingID}
    defaults: { _controller: SDCoreBundle:QueryBooking:modify }
    requirements:
        queryBookingID: \d+

sd_core_queryBooking_delete:
    path:     /queryBooking/delete/{queryBookingID}
    defaults: { _controller: SDCoreBundle:QueryBooking:delete }
    requirements:
        queryBookingID: \d+

sd_core_planning_display:
    path:     /planning/display
    defaults: { _controller: SDCoreBundle:Planning:index }

sd_core_parameter_numberLinesColumns:
    path:     /setNumberLinesColumns/{bundleCode}/{entityCode}
    defaults: { _controller: SDCoreBundle:Parameter:numberLinesColumns }
