<?php
// src/CoreBundle/DataFixtures/ORM/LoadBooking_707.php

namespace UserBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

use SD\CoreBundle\Entity\Booking;

class LoadBooking_707 extends AbstractFixture implements OrderedFixtureInterface
{
    public function load(ObjectManager $manager)
    {
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-03 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-03 09:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14185', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-11 18:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-11 19:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14260', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-11 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-11 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14309', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-10 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-10 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14310', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-09 13:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-09 23:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14311', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-11 18:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-11 20:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14312', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-11 21:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-11 23:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14313', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-12 14:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-12 15:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14359', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-12 15:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-12 16:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14361', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-26 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-26 11:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14633', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-11-26 11:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-11-26 12:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14634', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-03 14:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-03 15:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14696', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-03 15:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-03 16:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14697', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-03 16:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-03 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14698', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-03 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-03 18:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14699', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-15 20:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-15 21:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14964', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15031', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-21 13:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-21 23:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15032', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-22 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-22 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15033', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-23 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-23 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15034', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-27 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-27 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15035', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-28 13:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-28 23:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15036', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-29 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-29 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15037', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-30 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-30 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15038', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 18:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15056', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 18:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 19:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15057', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-27 20:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-27 21:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15160', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-27 21:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-27 22:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15161', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-01-07 15:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-01-07 16:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15352', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-01-07 16:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-01-07 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15353', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-04-13 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-04-13 18:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-17310', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-06-04 14:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-06-04 15:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18070', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-06-04 15:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-06-04 16:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18071', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-07-01 18:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-07-01 20:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18481', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-07-06 18:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-07-06 19:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18542', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-07-06 19:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-07-06 20:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18543', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-07-12 19:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-07-12 20:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18593', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-07-12 20:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-07-12 21:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18594', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-07-17 19:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-07-17 20:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18642', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-07-17 20:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-07-17 21:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18643', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-07-17 21:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-07-17 22:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18644', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-10-29 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-10-29 11:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-20538', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-10-29 11:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-10-29 12:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-20539', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-01-25 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-01-25 23:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-21611', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-03-18 15:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-03-18 16:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-22820', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-03-18 16:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-03-18 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-22821', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-03-24 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-03-24 09:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-22961', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-03-25 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-03-25 09:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-22962', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-03-25 09:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-03-25 23:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-22963', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-03-24 09:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-03-24 23:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-22964', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-04-08 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-04-08 23:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-22965', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-04-15 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-04-15 23:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-23355', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-550'), $this->getReference('resource-2465')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-05-06 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-05-06 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-23356', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-707'), $this->getReference('planification-551'), $this->getReference('resource-2485')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-05-06 08:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-05-06 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-23357', $booking);
    }

    public function getOrder()
    {
    return 59;
    }
}
