<?php
// src/CoreBundle/DataFixtures/ORM/LoadBooking_691.php

namespace UserBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

use SD\CoreBundle\Entity\Booking;

class LoadBooking_691 extends AbstractFixture implements OrderedFixtureInterface
{
    public function load(ObjectManager $manager)
    {
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Call ADLP'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-06-07 14:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-06-07 15:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12011', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-06-09 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-06-09 10:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12017', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('SACD'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-06-09 15:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-06-09 15:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12048', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Call SOMFY'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-06-13 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-06-13 11:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12091', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Mickaël Gomes pour SACD'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-06-21 16:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-06-21 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12232', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Mickaël pour la SACD'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-06-21 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-06-21 17:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12233', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-07-08 16:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-07-08 16:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12407', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-07-08 16:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-07-08 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12408', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('CCI Nord de France  Laurent - Corinne'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-07-19 11:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-07-19 12:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12446', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Mickaël Gomes KPC_FORTUNEO'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-08-30 17:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-08-30 18:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-12933', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('ONP'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-09-07 11:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-09-07 12:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-13097', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-09-07 14:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-09-07 15:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-13098', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Comité projet N°2 ONP'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-09-16 10:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-09-16 11:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-13285', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Comité projet ONP'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-09-23 10:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-09-23 11:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-13287', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('ONP - Coproj'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-09-30 10:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-09-30 11:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-13288', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('ONP'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-10-10 16:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-10-10 17:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-13712', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('ONP'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-10-17 16:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-10-17 19:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-13713', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('ONP'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-10-28 10:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-10-28 11:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-13714', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('RESA ASSU2000'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-10-14 10:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-10-14 11:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-13716', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-05 09:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-05 10:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14816', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-05 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-05 10:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14817', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Gilles + emmanuel + TCL'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-06 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-06 11:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14822', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('GILLES'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-05 15:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-05 17:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-14823', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('LE POINT'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-16 14:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-16 14:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15010', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('LE POINT'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-19 12:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-19 12:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15011', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('LE POINT'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-19 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-19 17:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15012', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('LE POINT'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 12:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 12:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15013', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('LE POINT'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-20 17:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15014', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('LE POINT'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-21 12:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-21 12:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15015', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('LE POINT'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-21 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-21 17:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15016', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('LE POINT'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-22 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-22 17:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15017', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('LE POINT'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2016-12-23 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2016-12-23 17:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-15018', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-02-06 14:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-02-06 15:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-16081', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('TCL Corinne'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-02-16 11:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-02-16 12:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-16244', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('iman'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-02-21 14:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-02-21 16:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-16387', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Point Fortuneo'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-02-28 17:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-02-28 18:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-16389', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Laurent MRS'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-03-16 16:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-03-16 20:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-16784', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Mickaël Gomes pour SACD'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-03-29 10:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-03-29 10:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-17013', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Paula'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-04-11 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-04-11 18:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-17223', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('KPC Marseille - Laurent'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-04-12 17:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-04-12 19:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-17311', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Résa Emmanuel pour MTP'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-05-19 15:30:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-05-19 16:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-17821', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Laurent SIROT KPC AIX'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-06-20 16:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-06-20 19:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-18341', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-11-14 11:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-11-14 12:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-20803', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setNote('Laurent'); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2017-11-15 14:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2017-11-15 14:30:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-20846', $booking);
$booking = new Booking($this->getReference('user-1'), $this->getReference('file-691'), $this->getReference('planification-545'), $this->getReference('resource-2393')); $booking->setBeginningDate(date_create_from_format('Y-m-d H:i:s','2018-02-14 14:00:00')); $booking->setEndDate(date_create_from_format('Y-m-d H:i:s','2018-02-14 16:00:00')); $manager->persist($booking); $manager->flush(); $this->addReference('booking-22296', $booking);
    }

    public function getOrder()
    {
    return 56;
    }
}
