<?php
// src/CoreBundle/DataFixtures/ORM/LoadBookingUser_492.php

namespace UserBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;

use SD\CoreBundle\Entity\BookingUser;

class LoadBookingUser_492 extends AbstractFixture implements OrderedFixtureInterface
{
    public function load(ObjectManager $manager)
    {
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3512'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3513'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3524'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3525'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3526'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3527'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3528'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3529'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3610'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3610'), $this->getReference('userFile-819')); $bookingUser->setOrder(2); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3701'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3788'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3839'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-3989'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4275'), $this->getReference('userFile-813')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4284'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4332'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4388'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4449'), $this->getReference('userFile-816')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4450'), $this->getReference('userFile-816')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4495'), $this->getReference('userFile-816')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4496'), $this->getReference('userFile-816')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4497'), $this->getReference('userFile-816')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4498'), $this->getReference('userFile-816')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4514'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4515'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4516'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4517'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4518'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4519'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4520'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4521'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4522'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4580'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4581'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4701'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4702'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4793'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4794'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-4835'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-5138'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-5432'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-5433'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-5807'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-5807'), $this->getReference('userFile-685')); $bookingUser->setOrder(2); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-5885'), $this->getReference('userFile-813')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6197'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6197'), $this->getReference('userFile-685')); $bookingUser->setOrder(2); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6421'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6523'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6619'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6684'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6782'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6783'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6784'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6785'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6802'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6848'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-6936'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7091'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7092'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7113'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7114'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7115'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7145'), $this->getReference('userFile-813')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7275'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7276'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7386'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7387'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7490'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-7491'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-8187'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-8188'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-10235'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-10613'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11261'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11262'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11263'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11264'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11276'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11277'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11278'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11279'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11280'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11281'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11282'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11283'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11284'), $this->getReference('userFile-813')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11285'), $this->getReference('userFile-813')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11286'), $this->getReference('userFile-813')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11404'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11405'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11406'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11407'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11552'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11789'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11807'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11808'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11842'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11858'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11859'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11860'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11861'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11925'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11962'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-11999'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12038'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12039'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12040'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12041'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12062'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12070'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12093'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12218'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12219'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12246'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12343'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12680'), $this->getReference('userFile-1169')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12681'), $this->getReference('userFile-1169')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12682'), $this->getReference('userFile-1169')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12760'), $this->getReference('userFile-1169')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12780'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-12930'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-13050'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-13167'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-13802'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-13830'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-13920'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-13921'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-13923'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-13924'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-14012'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-14013'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-14224'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-14225'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-14319'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-14320'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18027'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18028'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18049'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18050'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18150'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18151'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18157'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18158'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18219'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18241'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18243'), $this->getReference('userFile-1167')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18244'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18245'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18246'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18247'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18248'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18249'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18250'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18287'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18288'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-18759'), $this->getReference('userFile-684')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-19787'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-19788'), $this->getReference('userFile-819')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-20094'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-20317'), $this->getReference('userFile-1891')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-20321'), $this->getReference('userFile-1891')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-23984'), $this->getReference('userFile-811')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
$bookingUser = new BookingUser($this->getReference('user-1'), $this->getReference('booking-24001'), $this->getReference('userFile-1170')); $bookingUser->setOrder(1); $manager->persist($bookingUser); $manager->flush();
    }

    public function getOrder()
    {
    return 22;
    }
}
